
on:
  push:
    branches:
      - main

jobs:

  deploy:
    name: Deploy Service
    environment:  test-systemd-service
    runs-on: ubuntu-latest
    steps:

    - name: Checkout main
      uses: actions/checkout@v2

    - name: copy service
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        # port: ${{ secrets.PORT }}
        source: "services/*.service"
        target: "/etc/systemd/system/"
        strip_components: 1

    - name: copy files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        # port: ${{ secrets.PORT }}
        source: "files/*"
        target: "/sbin/primary.service/"
        strip_components: 1

    - name: reload and enable service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        # port: ${{ secrets.PORT }}
        script: systemctl daemon-reload && sudo systemctl enable primary.service && systemctl restart primary.service
